#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=36
#PBS -N Compare_nitrogen_deNovo
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1


compare_categories.py \
--method adonis \
-i ~/2018_02_smb/deNovo/otu_table.biom \
-o ~/2018_02_smb/deNovoNitrogen \
-c SampleNitrogen \
-m ~/2018_02_smb/map.tsv \
-n 999
