#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=36
#PBS -N Core_micro_Compare_categories_X
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
module load R-3.3.1-gcc-6.2.0-zjrjm3s
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1


compare_categories.py \
--method adonis \
-i ~/CoreDiv_CoreMicro_DeNovo/bdiv_even765/bray_curtis_dm.txt \
-o ~/CoreMicrobiome_Compare_X \
-c X \
-m ~/2018_02_smb/map.tsv \
-n 999
