#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N closed_GG_Core_diversity_analyses
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time core_diversity_analyses.py \
-i ~/2018_02_smb/closed/otu_table.biom \
-o ~/2018_02_smb/GG_CoreAnalyses \
-m ~/2018_02_smb/map.tsv \
-e 605 \
-t ~/2018_02_smb/closed/97_otus.tree

source deactivate
