#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=36
#PBS -N Core_diversity_analyses_GG_closed
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

core_diversity_analyses.py \
-i ~/2018_02_smb/deNovo/otu_table.biom \
-o ~/2018_02_smb/CoreAnalyses \
-m ~/2018_02_smb/map.tsv \
-e 605 \
-t ~/2018_02_smb/closed/97_otus.tree \
-O 9 \
-a
