#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=24
#PBS -N Core_diversity_analyses_novo
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

core_diversity_analyses.py \
-i ~/2018_02_smb/ \
-o ~/2018_02_smb/CoreAnalyses \
-m ~/2018_02_smb/map.tsv \
-e 765 \
-O 12 \
-a \
--nonphylogenetic_diversity
