#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=36
#PBS -N GreenGenes_closed_OTU_picking_2018
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time pick_closed_reference_otus.py \
-i ~/2018_02_smb/split_library/seqs.fna \
-o ~/2018_02_smb/closed \
-O 9 \
-a
