#!/bin/bash --login
#PBS -l walltime=09:00:00
#PBS -l select=1:ncpus=56
#PBS -N Novo_Core_diversity_analyses
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time core_diversity_analyses.py \
-i ~/2018_02_smb/deNovo/otu_table.biom \
-o ~/2018_02_smb/OpenCoreAnalyses \
-m ~/2018_02_smb/map.tsv \
-t ~/2018_02_smb/deNovo/rep_set.tre \
-e 765 \
-O 14 \
-a

source deactivate
