#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=24
#PBS -N Silva_open_OTU_picking_2018
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time pick_open_reference_otus.py \
-i ~/2018_02_smb/split_library/seqs.fna \
-o ~/2018_02_smb/open \
-r ~/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-O 3 \
-a
