#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N Demultiplexing_2018
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time split_libraries_fastq.py \
-m ~/2018_02_smb/map.tsv \
-i ~/2018_02_smb/SeqPrep_joined/seqprep_assembled.fastq.gz \
-b ~/2018_02_smb/SeqPrep_joined/seqprep_assembled.fastq_barcodes.fastq \
-o ~/2018_02_smb/split_library/ \
-q 19 \
--rev_comp_barcode --rev_comp_mapping_barcodes

source deactivate
